const data = {
  products: [
    {
      _id: "1",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product1.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "2",
      name: "AC",
      category: "Jogo",
      image: "/images/product2.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "3",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product3.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "4",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product4.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "5",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product5.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "66",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product6.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "7",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product7.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "8",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product8.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "9",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product9.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
    {
      _id: "10",
      name: "Harry Potter",
      category: "Livro",
      image: "/images/product10.jpg",
      price: 30,
      brand: "Marca",
      rating: "5",
      numReviews: 10,
      description: "capa dura",
    },
  ],
};
export default data;
